// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Framework Introduction',
      items: ['intro/Node-Advantages'],
    },
    {
      type: 'category',
      label: 'Framework Database',
      items: ['database/Lucidchart', 'database/Project_DB_Base_DB_Mapper'],
    },
    {
      type: 'category',
      label: 'Framework Backend',
      items: [
        'backend/UBS-intro',
        {
          type: 'category',
          label: 'Github Workflows',
          items: ['backend/githubWorkflows/ai-reviewer', 'backend/githubWorkflows/ai-agent'],
        },
        {
          type: 'category',
          label: 'Integrations',
          items: ['backend/Socket', 'backend/Payments', 'backend/local-whisper-setup'],
        },
        'backend/FAQs'
    
      ],
    },
    {
      type: 'category',
      label: 'Framework Frontend',
      items: ['frontend/UBS-intro'],
    },
    {
      type: 'category',
      label: 'Framework Agents',
      items: ['agents/agent-issue-format', 'agents/claude-github-issues-agent'],
    },
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-page', 'tutorial-basics/deploy-your-site', 'tutorial-basics/markdown-features'],
    },
    {
      type: 'category',
      label: 'Projects',
      items: [
        {
          type: 'category',
          label: 'Badar HMS',
          items: [
            {
              type: 'category',
              label: 'V1',
              items: [
                'projects/badar-hms/v1/OPERA_PMS_Integration_Solutions'              
              ]
            },
            {
              type: 'category',
              label: 'V2',
              items: [
                'projects/badar-hms/v2/OPERA_PMS_Integration_Solutions_v2'              
              ]
            },
            {
              type: 'category',
              label: 'V3',
              items: [
                'projects/badar-hms/v3/OPERA_PMS_Integration_Solutions_v3'              
              ]
            },
            {
              type: 'category',
              label: 'V4',
              items: [
                'projects/badar-hms/v4/OPERA_PMS_Integration_Solutions_v4'              
              ]
            },
            'projects/badar-hms/Opera_Config',
          ]
        }
      ],
    }
  ],
};

export default sidebars;
