// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'init',
    {
      type: 'category',
      label: 'Framework Introduction',
      items: ['intro/UBS_Framework_Features', 'intro/Node-Advantages'],
    },
    {
      type: 'category',
      label: 'Framework Database',
      items: ['database/Lucidchart', 'database/Project_DB_Base_DB_Mapper'],
    },
    {
      type: 'category',
      label: 'Framework Backend',
      items: [
        'backend/UBS-intro',
        'backend/tenancy',
        {
          type: 'category',
          label: 'Github Workflows',
          items: ['backend/githubWorkflows/ai-reviewer', 'backend/githubWorkflows/ai-agent'],
        },
        {
          type: 'category',
          label: 'Integrations',
          items: ['backend/Socket', 'backend/Payments', 'backend/local-whisper-setup'],
        },
        'backend/FAQs'

      ],
    },
    {
      type: 'category',
      label: 'Framework Frontend',
      items: ['frontend/UBS-intro'],
    },
    {
      type: 'category',
      label: 'Framework Agents',
      items: ['agents/agent-issue-format', 'agents/claude-github-issues-agent'],
    },
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-page', 'tutorial-basics/deploy-your-site', 'tutorial-basics/markdown-features'],
    },
    {
      type: 'category',
      label: 'HMS Documentation',
      items: [
        {
          type: 'category',
          label: 'Guest APIs',
          items: [
            {
              type: 'category',
              label: 'Guest Booking Flow',
              items: [
                'hms-documentation/guest-apis/guest-booking-flow/guest-booking-flow',
              ],
            },
            {
              type: 'category',
              label: 'Guest Upcoming Bookings',
              items: [
                'hms-documentation/guest-apis/guest-bookings-upcoming/guest-bookings-upcoming',
              ],
            },
            {
              type: 'category',
              label: 'Guest Current Booking',
              items: [
                'hms-documentation/guest-apis/guest-bookings-current/guest-bookings-current',
              ],
            },
            {
              type: 'category',
              label: 'Guest Booking Check In',
              items: [
                'hms-documentation/guest-apis/guest-booking-checkin/guest-booking-checkin',
              ],
            },
            {
              type: 'category',
              label: 'Guest Booking Check Out',
              items: [
                'hms-documentation/guest-apis/guest-booking-checkout/guest-booking-checkout',
              ],
            },
            {
              type: 'category',
              label: 'Guest Booking Cancel',
              items: [
                'hms-documentation/guest-apis/guest-booking-cancel/guest-booking-cancel',
              ],
            },
            {
              type: 'category',
              label: 'Guest Bookings Service',
              items: [
                'hms-documentation/guest-apis/guest-bookings-service/guest-bookings-service',
              ],
            },
            {
              type: 'category',
              label: 'Guest Favorites',
              items: [
                'hms-documentation/guest-apis/guest-favorites/guest-favorites',
              ],
            },
            {
              type: 'category',
              label: 'Guest Services',
              items: [
                'hms-documentation/guest-apis/guest-services/guest-services',
              ],
            },
            {
              type: 'category',
              label: 'Guest Onboarding KYC',
              items: [
                'hms-documentation/guest-apis/guest-onboarding-kyc/guest-onboarding-kyc',
              ],
            },
            {
              type: 'category',
              label: 'Guest Booking Reschedule',
              items: [
                'hms-documentation/guest-apis/guest-booking-reschedule/guest-booking-reschedule',
              ],
            },
            {
              type: 'category',
              label: 'Guest Scheduler',
              items: [
                'hms-documentation/guest-apis/guest-scheduler/guest-scheduler',
              ],
            },
            {
              type: 'category',
              label: 'Guest Service Categories',
              items: [
                'hms-documentation/guest-apis/guest-service-categories/guest-service-categories',
              ],
            },
            {
              type: 'category',
              label: 'Guest Check-In Eligibility',
              items: [
                'hms-documentation/guest-apis/guest-checkin-eligibility/guest-checkin-eligibility',
              ],
            },
            {
              type: 'category',
              label: 'Guest Token Refresh',
              items: [
                'hms-documentation/guest-apis/guest-token-refresh/guest-token-refresh',
              ],
            },
            {
              type: 'category',
              label: 'Guest Email Notifications',
              items: [
                'hms-documentation/guest-apis/guest-email-notifications/guest-email-notifications',
              ],
            },
            {
              type: 'category',
              label: 'Guest Networking Details',
              items: [
                'hms-documentation/guest-apis/guest-networking-details/guest-networking-details',
              ],
            },
            {
              type: 'category',
              label: 'Fetch Guest Documents',
              items: [
                'hms-documentation/guest-apis/fetch-guest-documents/fetch-guest-documents',
              ],
            },
            {
              type: 'category',
              label: 'Fetch Guest Document Tags',
              items: [
                'hms-documentation/guest-apis/fetch-guest-document-tags/fetch-guest-document-tags',
              ],
            }
          ],
        },
        {
          type: 'category',
          label: 'Payment Gateways',
          items: [
            {
              type: 'category',
              label: 'Moyasar',
              items: [
                'hms-documentation/payment-gateways/moyasar/setup',
                'hms-documentation/payment-gateways/moyasar/payment-flow',
                'hms-documentation/payment-gateways/moyasar/webhook',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Tenant Governance',
          items: [
            'hms-documentation/tenant-governance/README',
            'hms-documentation/tenant-governance/tenant-governance-model/governance-model',
            'hms-documentation/tenant-governance/per-tenant-cloning/per-tenant-cloning',
            'hms-documentation/tenant-governance/per-tenant-resource-assignment/resource-assignments',
            {
              type: 'category',
              label: 'Config Keys',
              items: [
                'hms-documentation/tenant-governance/config-keys/config-keys',
                'hms-documentation/tenant-governance/config-keys/config-keys-catalog/config-keys-catalog',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Projects',
      items: [
        {
          type: 'category',
          label: 'Badar HMS',
          items: [
            {
              type: 'category',
              label: 'V1',
              items: [
                'projects/badar-hms/v1/OPERA_PMS_Integration_Solutions'              
              ]
            },
            {
              type: 'category',
              label: 'V2',
              items: [
                'projects/badar-hms/v2/OPERA_PMS_Integration_Solutions_v2'              
              ]
            },
            {
              type: 'category',
              label: 'V3',
              items: [
                'projects/badar-hms/v3/OPERA_PMS_Integration_Solutions_v3'              
              ]
            },
            {
              type: 'category',
              label: 'V4',
              items: [
                'projects/badar-hms/v4/OPERA_PMS_Integration_Solutions_v4'              
              ]
            },
            'projects/badar-hms/Opera_Config',
          ]
        }
      ],
    }
  ],
};

export default sidebars;
