flowchart TD

    A[Start]

    --> B[Create Encryption Key]

    --> C{Access Token Enabled?}

    C -->|Yes| D[Append Access Token]
    C -->|No| E

    D --> E{Plain Key Enabled?}

    E -->|Yes| F[Append Plain Key]
    E -->|No| G

    F --> G{Platform Encryption Enabled?}

    G -->|Yes| H[Retrieve Platform Key]

    H --> I[Append Platform Key]

    G -->|No| J[Generate Final Encryption Key]

    I --> J

    J --> K[Decrypt Request Payload]