flowchart TD

    A[Client Request] --> B[Query Resolver]
    B --> C{Pagination Enabled?}

    C -->|Yes| D[Execute Query With Pagination]
    C -->|No| K[Execute Query]

    D --> F[Read Pagination Parameters]
    F --> G[Apply Search]
    G --> H[Apply Filters]
    H --> I[Apply Sorting]
    I --> J[Generate Final SQL Query]
    J --> K[Execute Query]

    K --> L[(Database)]
    L --> M[Return Results]