sequenceDiagram

    participant Client
    participant Authentication
    participant Authorization
    participant APIObject
    participant Database

    Client->>Authentication: API Request

    Authentication-->>Authorization: User Authenticated

    Authorization->>APIObject: Read Required Permission

    Authorization->>Authorization: Validate Permission

    alt Permission Granted

        Authorization->>Database: Continue Request Processing

        Database-->>Client: Response

    else Permission Denied

        Authorization-->>Client: 403 Forbidden

    end