import { useState } from 'react'
import { Check, Plus, Trash2, X, ChevronLeft } from 'lucide-react'
import { c, card, txt, muted, divider, inputCls, chipMint, chipIndigo, chipAmber, chipViolet } from '../lib'
import type { Screen, Theme } from '../types'

interface Props { navigate: (s: Screen) => void; theme: Theme }

const STAGES = ['Pre-Meeting', 'Transcribe', 'Analyze', 'Tasks', 'Report']

interface Task { task: string; assignee: string; priority: 'High' | 'Medium' | 'Low'; repo: string }

const INIT_TASKS: Task[] = [
  { task: 'Complete OAuth2 PKCE flow implementation', assignee: 'James R.', priority: 'High', repo: 'auth-service' },
  { task: 'Ship ERD mapper to staging environment', assignee: 'Ana T.', priority: 'High', repo: 'tenant-admin-ui' },
  { task: 'Write migration rollback scripts', assignee: 'Dev P.', priority: 'Medium', repo: 'db-migrations' },
  { task: 'Add rate limiting to /api/v2 routes', assignee: 'Chris L.', priority: 'Low', repo: 'api-gateway' },
]

const PRIORITY_STYLES: Record<string, string> = {
  High: 'chip bg-red-500/12 text-red-400 border border-red-500/20',
  Medium: 'chip bg-amber-500/12 text-amber-400 border border-amber-500/20',
  Low: 'chip bg-emerald-500/12 text-emerald-400 border border-emerald-500/20',
}
const PRIORITY_STYLES_LIGHT: Record<string, string> = {
  High: 'chip bg-red-50 text-red-600 border border-red-100',
  Medium: 'chip bg-amber-50 text-amber-600 border border-amber-100',
  Low: 'chip bg-emerald-50 text-emerald-600 border border-emerald-100',
}

export default function MeetingAnalyze({ navigate, theme }: Props) {
  const [tasks, setTasks] = useState<Task[]>(INIT_TASKS)
  const [prompt, setPrompt] = useState('')
  const [toast, setToast] = useState(false)
  const d = theme === 'dark'

  const addRow = () => setTasks(t => [...t, { task: '', assignee: '', priority: 'Medium', repo: '' }])
  const removeRow = (i: number) => setTasks(t => t.filter((_, j) => j !== i))
  const update = (i: number, k: keyof Task, v: string) =>
    setTasks(t => t.map((row, j) => j === i ? { ...row, [k]: v } : row))

  const handleApprove = () => { setToast(true); setTimeout(() => setToast(false), 4500) }

  const pStyle = (p: string) => d ? PRIORITY_STYLES[p] : PRIORITY_STYLES_LIGHT[p]

  return (
    <div className={c('min-h-full', d ? 'aurora-dark' : 'aurora-light')}>
      <div className="max-w-[1240px] mx-auto px-10 py-10">
        {/* Stage nav */}
        <div className={c('flex items-center rounded-2xl overflow-hidden mb-8', card(theme))}>
          {STAGES.map((s, i) => (
            <button key={i}
              onClick={() => i === 1 && navigate('meetings-transcribe')}
              className={c(
                'flex-1 flex items-center justify-center gap-2 py-4 text-sm font-semibold relative tr',
                i === 2 ? 'text-indigo-500' :
                i < 2 ? d ? 'text-emerald-400' : 'text-emerald-600' :
                d ? 'text-white/22' : 'text-slate-300'
              )}>
              {i < 2 && <Check size={13} />}
              {s}
              {i === 2 && <div className="absolute bottom-0 inset-x-0 h-0.5 bg-indigo-500" />}
            </button>
          ))}
        </div>

        {/* AI Summary card */}
        <div className={c(card(theme), 'p-6 mb-5')}>
          {/* Header */}
          <div className="flex items-center gap-3 mb-5">
            <div className="w-8 h-8 rounded-xl flex items-center justify-center text-sm"
              style={{ background: '#4F46E5' }}>🤖</div>
            <div>
              <p className={c('font-bold text-[15px]', txt(theme))}>AI Summary</p>
              <p className={c('text-xs', muted(theme))}>Generated by Claude 3.5 Sonnet</p>
            </div>
            <span className={c('ml-auto', chipIndigo(theme))}>claude-3-5-sonnet</span>
          </div>

          {/* Summary paragraph */}
          <p className={c('text-sm leading-relaxed mb-5', muted(theme))}>
            The Q3 sprint planning session aligned the team on four primary workstreams: <strong className={d ? 'text-white/80 font-semibold' : 'text-slate-700 font-semibold'}>tenant migration</strong> (highest priority), <strong className={d ? 'text-white/80 font-semibold' : 'text-slate-700 font-semibold'}>ERD mapper release</strong>, auth service OAuth2 PKCE completion, and API gateway rate limiting. James confirmed the OAuth2 implementation will be complete by Friday EOD. Ana flagged a dependency on the database schema upload feature before ERD mapper can ship to staging.
          </p>

          {/* Tinted chip groups */}
          <div className="flex flex-wrap gap-x-6 gap-y-3 mb-5">
            {[
              { label: 'Projects', chips: ['auth-service', 'api-gateway', 'tenant-admin-ui', 'db-migrations'], fn: chipIndigo },
              { label: 'Platforms', chips: ['Staging', 'Production', 'AWS Lambda'], fn: chipViolet },
              { label: 'Decisions', chips: ['OAuth2 by Friday', 'ERD mapper blocked', 'Migration is P1'], fn: chipAmber },
            ].map(g => (
              <div key={g.label} className="flex items-center gap-2 flex-wrap">
                <span className={c('section-kicker', d ? 'text-white/28' : 'text-slate-300')}>{g.label}:</span>
                {g.chips.map(chip => (
                  <span key={chip} className={g.fn(theme)}>{chip}</span>
                ))}
              </div>
            ))}
          </div>

          {/* Prompt input */}
          <div className={c('flex gap-2 pt-5 border-t', divider(theme))}>
            <input value={prompt} onChange={e => setPrompt(e.target.value)}
              placeholder="Ask Claude for clarity… e.g. 'What blockers were mentioned?'"
              className={c(inputCls(theme), 'flex-1 text-sm')} />
            <button className="btn-primary px-4 py-2.5 text-sm rounded-xl whitespace-nowrap">Ask Claude</button>
          </div>
        </div>

        {/* Tasks table */}
        <div className={c(card(theme), 'p-6')}>
          <div className="flex items-center justify-between mb-5">
            <div>
              <p className={c('font-bold text-[15px]', txt(theme))}>Action Items</p>
              <p className={c('text-xs mt-0.5', muted(theme))}>{tasks.length} tasks extracted from transcript</p>
            </div>
            <button onClick={addRow}
              className={c('flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-xl tr',
                d ? 'text-indigo-400 hover:bg-indigo-500/12' : 'text-indigo-600 hover:bg-indigo-50')}>
              <Plus size={13} /> Add Row
            </button>
          </div>

          {/* Column headers */}
          <div className={c('grid grid-cols-[3fr_1.5fr_100px_1.5fr_40px] gap-3 px-3 pb-2.5 border-b section-kicker',
            divider(theme), d ? 'text-white/25' : 'text-slate-300')}>
            <span>Task</span><span>Assignee</span><span>Priority</span><span>Repository</span><span />
          </div>

          {/* Rows */}
          <div className="flex flex-col gap-0.5 mt-1.5 mb-5">
            {tasks.map((t, i) => (
              <div key={i} className={c(
                'grid grid-cols-[3fr_1.5fr_100px_1.5fr_40px] gap-3 items-center px-3 py-2 rounded-xl tr',
                d ? 'hover:bg-white/[0.025]' : 'hover:bg-slate-50'
              )}>
                <input value={t.task} onChange={e => update(i, 'task', e.target.value)}
                  placeholder="Task description…"
                  className={c(inputCls(theme, 'py-1.5 text-xs'))} />
                <input value={t.assignee} onChange={e => update(i, 'assignee', e.target.value)}
                  placeholder="Name"
                  className={c(inputCls(theme, 'py-1.5 text-xs'))} />
                <select value={t.priority} onChange={e => update(i, 'priority', e.target.value as any)}
                  className={c(inputCls(theme, 'py-1.5 text-xs'))}>
                  <option>High</option><option>Medium</option><option>Low</option>
                </select>
                <input value={t.repo} onChange={e => update(i, 'repo', e.target.value)}
                  placeholder="repo-name"
                  className={c(inputCls(theme, 'py-1.5 text-xs mono'))} />
                <button onClick={() => removeRow(i)}
                  className={c('p-1.5 rounded-lg tr',
                    d ? 'text-white/18 hover:text-red-400 hover:bg-red-500/10' : 'text-slate-300 hover:text-red-500 hover:bg-red-50')}>
                  <Trash2 size={13} />
                </button>
              </div>
            ))}
          </div>

          {/* CTA row */}
          <div className={c('flex items-center justify-between pt-5 border-t', divider(theme))}>
            <button className={c(
              'btn-outline-indigo flex items-center gap-2 px-5 py-2.5 text-sm',
              d ? 'dark-variant' : ''
            )}>
              Reject All
            </button>
            <button onClick={handleApprove}
              className="btn-primary flex items-center gap-2 px-6 py-2.5 text-sm">
              <Check size={14} /> Approve All → Create GitHub Issues
            </button>
          </div>
        </div>
      </div>

      {/* Toast */}
      {toast && (
        <div className="fixed bottom-6 right-6 toast-in flex items-center gap-3 px-5 py-3.5 rounded-2xl text-sm font-semibold text-white z-50"
          style={{ background: '#4F46E5', boxShadow: '0 4px 20px rgba(79,70,229,0.35)' }}>
          <Check size={15} />
          3 issues created, 1 duplicate skipped
          <button onClick={() => setToast(false)} className="ml-1 opacity-55 hover:opacity-100 tr">
            <X size={14} />
          </button>
        </div>
      )}
    </div>
  )
}
